[doc] add a README doc for otbr docker for common issues
openthread/ot-br-posix pull request #2641
Opened 2024-12-16 08:12 UTC by Irving-cl

This PR adds a README doc for OTBR docker for common issues.

2024-12-19 05:58 UTC, Vyrastas requested changes

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +If `rsyslog` cannot start successfully (don't have response) during otbr docker image booting-up:
```suggestion
If `rsyslog` cannot start successfully (there is no response) during the OTBR Docker image boot up:
```

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +### rsyslog cannot start
Can you make this a level 2 header?

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +# OT BR Docker
OTBR Docker?

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +## Troubleshooting
Instead of this header, can you say something like, "This file contains troubleshooting for common issues with OTBR Docker."

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +This is caused by the high limit number of file descriptors (`LimitNOFILE`). The program of `rsyslog` will take a long time to run a for loop to close all open file descriptors when this limit is hig
```suggestion
This is caused by the high limit number of file descriptors (`LimitNOFILE`). `rsyslog` takes a long time to run a for loop to close all open file descriptors when this limit is high (for example, `1073741816`).
```

2024-12-19 05:58 UTC, Vyrastas commented on etc/docker/README.md
> +And then reload & restart the docker service:
```suggestion
And then reload & restart the `docker` service:
```

2024-12-20 05:49 UTC, Vyrastas approved these changes

2025-01-07 03:53 UTC, superwhd commented
@jwhui Could you take another look at this PR? I met the same issue when running BR tests and the solution worked well.

2025-01-07 05:32 UTC, jwhui approved these changes

2025-01-07 05:32 UTC, merged